INSERT INTO mypetstore.record (userid, records, isitem) VALUES ('j2ee', 'EST-4 -----------------------------------------------------------------------------2022-11-13 at 02:22:35 CST', 1);
INSERT INTO mypetstore.record (userid, records, isitem) VALUES ('j2ee', 'EST-5 -----------------------------------------------------------------------------2022-11-13 at 02:22:55 CST', 1);
INSERT INTO mypetstore.record (userid, records, isitem) VALUES ('2', 'EST-6 -----------------------------------------------------------------------------2022-11-13 at 14:20:32 CST', 1);
INSERT INTO mypetstore.record (userid, records, isitem) VALUES ('2', 'EST-6 -----------------------------------------------------------------------------2022-11-13 at 14:28:09 CST', 1);
INSERT INTO mypetstore.record (userid, records, isitem) VALUES ('2', 'EST-6 -----------------------------------------------------------------------------2022-11-13 at 14:30:25 CST', 1);
INSERT INTO mypetstore.record (userid, records, isitem) VALUES ('2', 'EST-26 -----------------------------------------------------------------------------2022-11-13 at 14:34:31 CST', 1);
INSERT INTO mypetstore.record (userid, records, isitem) VALUES ('j2ee', 'EST-4 -----------------------------------------------------------------------------2022-11-13 at 14:36:26 CST', 1);
INSERT INTO mypetstore.record (userid, records, isitem) VALUES ('j2ee', 'EST-6 -----------------------------------------------------------------------------2022-11-13 at 14:45:37 CST', 1);
INSERT INTO mypetstore.record (userid, records, isitem) VALUES ('j2ee', '登录', 0);
INSERT INTO mypetstore.record (userid, records, isitem) VALUES ('j2ee', '浏览DOGS', 0);
INSERT INTO mypetstore.record (userid, records, isitem) VALUES ('j2ee', '浏览K9-PO-02', 0);
INSERT INTO mypetstore.record (userid, records, isitem) VALUES ('j2ee', 'EST-8 -----------------------------------------------------------------------------2022-11-13 at 15:15:15 CST', 1);
INSERT INTO mypetstore.record (userid, records, isitem) VALUES ('j2ee', '登录', 0);
INSERT INTO mypetstore.record (userid, records, isitem) VALUES ('3', '登录 -----------------------------2022-11-13 at 15:24:20 CST', 0);
INSERT INTO mypetstore.record (userid, records, isitem) VALUES ('3', '浏览FISH -----------------------------2022-11-13 at 15:24:36 CST', 0);
INSERT INTO mypetstore.record (userid, records, isitem) VALUES ('3', '浏览FI-FW-01 -----------------------------2022-11-13 at 15:24:38 CST', 0);
INSERT INTO mypetstore.record (userid, records, isitem) VALUES ('3', 'EST-4 -----------------------------2022-11-13 at 15:24:39 CST', 1);
INSERT INTO mypetstore.record (userid, records, isitem) VALUES ('3', '加入购物车EST-4 -----------------------------2022-11-13 at 15:24:46 CST', 0);
INSERT INTO mypetstore.record (userid, records, isitem) VALUES ('3', '浏览FISH -----------------------------2022-11-13 at 15:25:04 CST', 0);
INSERT INTO mypetstore.record (userid, records, isitem) VALUES ('3', '浏览FI-FW-01 -----------------------------2022-11-13 at 15:25:06 CST', 0);
INSERT INTO mypetstore.record (userid, records, isitem) VALUES ('3', 'EST-4 -----------------------------2022-11-13 at 15:25:07 CST', 1);
INSERT INTO mypetstore.record (userid, records, isitem) VALUES ('3', '下单EST-4 -----------------------------2022-11-13 at 15:25:22 CST', 0);
